In [73]:
import numpy as np
import tensorflow as tf

In [74]:
train_data_x1 = np.arange(0, 100).reshape((100, 1))
train_data_x2 = np.arange(100, 200).reshape((100, 1))
train_data_x = np.hstack([train_data_x1, train_data_x2])
train_data_y = np.arange(200, 300).reshape((100, 1))

print(train_data_x.shape)
print(train_data_y.shape)

(100, 2)
(100, 1)


In [95]:
BATCHSIZE = 3
TRAINSIZE = 100

x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])
train_dataset = tf.data.Dataset.from_tensor_slices((x,y)).batch(BATCHSIZE).repeat()

train_data_x1 = np.arange(0, 100).reshape((100, 1))
train_data_x2 = np.arange(100, 200).reshape((100, 1))
train_data_x = np.hstack([train_data_x1, train_data_x2])
train_data_y = np.arange(200, 300).reshape((100, 1))

iter = train_dataset.make_initializable_iterator() # create the iterator
next_elements = iter.get_next()

train_init_op = iter.make_initializer(train_dataset)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # initialise iterator with train data
    sess.run(train_init_op, feed_dict = {x : train_data_x, y: train_data_y, batch_size: 16})
    for i in range(TRAINSIZE // BATCHSIZE):
        features, labels = sess.run(next_elements)
        print(features)
        print(labels)

[[  0. 100.]
 [  1. 101.]
 [  2. 102.]]
[[200.]
 [201.]
 [202.]]
[[  3. 103.]
 [  4. 104.]
 [  5. 105.]]
[[203.]
 [204.]
 [205.]]
[[  6. 106.]
 [  7. 107.]
 [  8. 108.]]
[[206.]
 [207.]
 [208.]]
[[  9. 109.]
 [ 10. 110.]
 [ 11. 111.]]
[[209.]
 [210.]
 [211.]]
[[ 12. 112.]
 [ 13. 113.]
 [ 14. 114.]]
[[212.]
 [213.]
 [214.]]
[[ 15. 115.]
 [ 16. 116.]
 [ 17. 117.]]
[[215.]
 [216.]
 [217.]]
[[ 18. 118.]
 [ 19. 119.]
 [ 20. 120.]]
[[218.]
 [219.]
 [220.]]
[[ 21. 121.]
 [ 22. 122.]
 [ 23. 123.]]
[[221.]
 [222.]
 [223.]]
[[ 24. 124.]
 [ 25. 125.]
 [ 26. 126.]]
[[224.]
 [225.]
 [226.]]
[[ 27. 127.]
 [ 28. 128.]
 [ 29. 129.]]
[[227.]
 [228.]
 [229.]]
[[ 30. 130.]
 [ 31. 131.]
 [ 32. 132.]]
[[230.]
 [231.]
 [232.]]
[[ 33. 133.]
 [ 34. 134.]
 [ 35. 135.]]
[[233.]
 [234.]
 [235.]]
[[ 36. 136.]
 [ 37. 137.]
 [ 38. 138.]]
[[236.]
 [237.]
 [238.]]
[[ 39. 139.]
 [ 40. 140.]
 [ 41. 141.]]
[[239.]
 [240.]
 [241.]]
[[ 42. 142.]
 [ 43. 143.]
 [ 44. 144.]]
[[242.]
 [243.]
 [244.]]
[[ 45. 145.]
 [ 46. 146.]

In [5]:
# Wrapping all together -> Switch between train and test set using Reinitializable iterator
EPOCHS = 10
# create a placeholder to dynamically switch between batch sizes
batch_size = tf.placeholder(tf.int64)

x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.placeholder(tf.float32, shape=[None,1])
train_dataset = tf.data.Dataset.from_tensor_slices((x,y)).batch(batch_size).repeat()
test_dataset = tf.data.Dataset.from_tensor_slices((x,y)).batch(batch_size) # always batch even if you want to one shot it
# using two numpy arrays
train_data = (np.random.sample((100,2)), np.random.sample((100,1)))
test_data = (np.random.sample((20,2)), np.random.sample((20,1)))

# create a iterator of the correct shape and type
iter = tf.data.Iterator.from_structure(train_dataset.output_types,
                                           train_dataset.output_shapes)
features, labels = iter.get_next()
# create the initialisation operations
train_init_op = iter.make_initializer(train_dataset)
test_init_op = iter.make_initializer(test_dataset)

# make a simple model
net = tf.layers.dense(features, 8, activation=tf.tanh) # pass the first value from iter.get_next() as input
net = tf.layers.dense(net, 8, activation=tf.tanh)
prediction = tf.layers.dense(net, 1, activation=tf.tanh)

loss = tf.losses.mean_squared_error(prediction, labels) # pass the second value from iter.get_net() as label
train_op = tf.train.AdamOptimizer().minimize(loss)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # initialise iterator with train data
    sess.run(train_init_op, feed_dict = {x : train_data[0], y: train_data[1], batch_size: 16})
    print('Training...')
    for i in range(EPOCHS):
        tot_loss = 0
        for _ in range(n_batches):
            _, loss_value = sess.run([train_op, loss])
            tot_loss += loss_value
        print("Iter: {}, Loss: {:.4f}".format(i, tot_loss / n_batches))
    # initialise iterator with test data
    sess.run(test_init_op, feed_dict = {x : test_data[0], y: test_data[1], batch_size:len(test_data[0])})
    print('Test Loss: {:4f}'.format(sess.run(loss)))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use keras.layers.dense instead.
Instructions for updating:
Use tf.cast instead.
Training...


NameError: name 'n_batches' is not defined